name: Deploy API to Staging

on:
  workflow_dispatch:
    # inputs:
    #   commit:
    #     description: "Branch/Commit ref"
    #     default: ""
    #     required: true
    #     type: string
    #

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Version
        # https://github.com/marketplace/actions/git-semantic-version
        id: version
        uses: paulhatch/semantic-version@v5.0.2
        with:
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"

      - name: Release Draft
        # https://github.com/ncipollo/release-action
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          name: Scorer API ${{ steps.version.outputs.version }}
          tag: ${{ steps.version.outputs.version_tag }}

      - name: Echo
        run: |
          echo tag ${{ steps.version.outputs.version_tag }}
          echo version ${{ steps.version.outputs.version }}
      - name: Release to Staging
        run: |
          echo "Staging Release Complete version: " ${{ steps.version.outputs.version_tag }}

    outputs:
      version_tag: ${{ steps.version.outputs.version_tag }}

  deploy:
    needs: [release]
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Release to Production
        run: |
          echo "Production Release Complete version: " ${{ needs.release.outputs.version_tag }}
