name: Deploy API to Production

on:
  workflow_dispatch:
    inputs:

env:
  TOKEN: ${{ secrets.TOKEN }}

permissions: write-all
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Gets latest created release info
        id: latest_release_info
        uses: lucianHymer/get-current-release-action@v1.9
        with:
          token: ${{ env.TOKEN }}
          owner: lucianHymer
          repo: workflowTest
      - name: Release
        # https://github.com/ncipollo/release-action
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          token: ${{ env.TOKEN }}
          tag: ${{ steps.latest_release_info.outputs.tag }}
          draft: false
          makeLatest: true
    outputs:
      tag: ${{ steps.latest_release_info.outputs.tag }}

  echo:
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo tag ${{ needs.release.outputs.tag }}
  deploy:
    permissions: write-all
    needs: [release]
    uses: lucianHymer/workflowTest/.github/workflows/build.yml@main
    with:
      owner: lucianHymer
      repo: workflowTest
      commitish: ${{ needs.release.outputs.tag }}
      token: ${{ env.TOKEN }}
