name: Deploy API to Production

on:
  workflow_dispatch:
    inputs:

permissions: write-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Gets latest created release info
        id: latest_release_info
        uses: lucianHymer/get-current-release-action@v1.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
