name: Deploy API to Production

on:
  workflow_dispatch:
    inputs:

permissions: write-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Release
        id: latest_release_info
        uses: pozetroninc/github-action-get-latest-release@v0.7.0
      - name: Echo
        run: |
          echo tag ${{ steps.latest_release_info.outputs.release }}
