name: Deploy API to Production

on:
  workflow_dispatch:
    inputs:

permissions: write-all
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Gets latest created release info
        id: latest_release_info
        uses: lucianHymer/get-current-release-action@v1.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        # https://github.com/ncipollo/release-action
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.latest_release_info.outputs.tag }}
          draft: false
          makeLatest: true

