name: Deploy API to Staging

on:
  workflow_dispatch:
    # inputs:
    #   commit:
    #     description: "Branch/Commit ref"
    #     default: ""
    #     required: true
    #     type: string
    #

jobs:
  release:
    permissions: write-all
    # needs: [deploy-staging]
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.commit }}
          fetch-depth: 0

      - name: Version
        # https://github.com/marketplace/actions/git-semantic-version
        id: version
        uses: paulhatch/semantic-version@v5.0.2
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          major_regexp_flags: ""
          minor_pattern: "(MINOR)"
          minor_regexp_flags: ""
          bump_each_commit: false
          user_format_type: "csv"

      - name: Release
        # https://github.com/ncipollo/release-action
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          name: Scorer API ${{ steps.version.outputs.version }}
          tag: ${{ steps.version.outputs.version_tag }}
          draft: true

      - name: Echo
        run: |
          echo tag ${{ steps.version.outputs.version_tag }}
          echo version ${{ steps.version.outputs.version }}

  test:
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Release
        id: latest_release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: lucianHymer/workflowTest
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.latest_release.outputs.tag }}
        run: |
          echo ${{env.RELEASE_VERSION}}
