name: Deploy API to Production

on:
  workflow_dispatch:
    inputs:

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Gets latest created release info
        id: latest_release_info
        uses: jossef/action-latest-release-info@v1.2.1

      - name: Echo
        run: |
          echo tag ${{steps.latest_release_info.outputs.tag_name}}
