name: Deploy API to Staging

on:
  workflow_dispatch:
    # inputs:
    #   commit:
    #     description: "Branch/Commit ref"
    #     default: ""
    #     required: true
    #     type: string
    #

jobs:
  release:
    permissions: write-all
    # needs: [deploy-staging]
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Version
        # https://github.com/marketplace/actions/git-semantic-version
        id: version
        uses: paulhatch/semantic-version@v5.0.2
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          major_regexp_flags: ""
          minor_pattern: "(MINOR)"
          minor_regexp_flags: ""
          bump_each_commit: false
          user_format_type: "csv"

      - name: Tag Draft
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}
          ref: main
          fetch-depth: 0
        run: |
          git tag -d draft-{{ steps.version.outputs.version }} || echo "Creating tag for the first time"
          git tag draft-{{ steps.version.outputs.version }}
          git remote set-url origin https://${{ secrets.TOKEN }}@github.com/${{ inputs.owner }}/${{ inputs.repo }}.git
          git push --follow-tags origin

      - name: Release Draft
        # https://github.com/ncipollo/release-action
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          name: Scorer API ${{ steps.version.outputs.version }}
          tag: ${{ steps.version.outputs.version_tag }}
          draft: true

      - name: Echo
        run: |
          echo tag ${{ steps.version.outputs.version_tag }}
          echo version ${{ steps.version.outputs.version }}

