name: Deploy API to Production

on:
  workflow_dispatch:
    inputs:

permissions: write-all
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Gets latest created release info
        id: latest_release_info
        uses: lucianHymer/get-current-release-action@v1.7
        with:
          token: ${{ env.GITHUB_TOKEN }}
      - name: Echo
        run: |
          echo tag ${{ steps.latest_release_info.outputs.tag }}
