name: Deploy API to Production

on:
  workflow_dispatch:
    inputs:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Gets latest created release info
        id: latest_release_info
        uses: lucianHymer/get-current-release-action
        with:
          token: ${{ env.GITHUB_TOKEN }}
