name: Deploy API to Staging

on:
  workflow_dispatch:
    # inputs:
    #   commit:
    #     description: "Branch/Commit ref"
    #     default: ""
    #     required: true
    #     type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set output
        id: vars
        run: echo "tag=$(git rev-list --tags --max-count=100 | xargs git describe --tags --match='v*.*' | grep -E '^v[0-9]+\.[0-9]+(\.[0-9]+)?$' | head -n1)" >> $GITHUB_OUTPUT
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo ${{env.RELEASE_VERSION}}
          LATEST_TAG=$(git rev-list --tags --max-count=100 | xargs git describe --tags --match='v*.*' | grep -E '^v[0-9]+\.[0-9]+(\.[0-9]+)?$' | head -n1)
          echo $LATEST_TAG
          echo `git rev-list --tags --max-count=100 | xargs git describe --tags --match='v*.*' | grep -E '^v[0-9]+\.[0-9]+(\.[0-9]+)?$' | head -n1`
