name: Build

on:
  workflow_call:
    inputs:
      commitish:
        required: true
        type: string
      owner:
        required: true
        type: string
      repo:
        required: true
        type: string


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - name: Fake build
        run: |
          git fetch
          git checkout -b build origin/build
          git reset --hard ${input.commitish}
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${owner}/${repo}.git
          git push origin build -f
