name: Build

on:
  workflow_call:
    inputs:
      commitish:
        required: true
        type: string
      owner:
        required: true
        type: string
      repo:
        required: true
        type: string


permissions: write-all
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}
          ref: main
          fetch-depth: 0
      - name: Fake build
        run: |
          echo ${{ inputs.commitish }}
          git fetch
          git checkout -b build 
          git reset --hard ${{ inputs.commitish }}
          git reset HEAD -- .github/workflows
          git remote set-url origin https://${{ secrets.TOKEN }}@github.com/${{ inputs.owner }}/${{ inputs.repo }}.git
          git push origin build -f
