name: Deploy to AWS

on:
  workflow_call:
    inputs:
      repository:
        description: "Repository in format owner/repo"
        required: true
        type: string
      refspec:
        description: "Commit ref"
        required: true
        type: string
      docker_tag:
        description: "Commit short SHA"
        required: true
        type: string
      env_name:
        required: true
        type: string
      domain:
        required: true
        type: string
    secrets:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        ECR_URL: ${{secrets.ECR_URL}}
        ROUTE53_ZONE_ID: ${{ secrets.ROUTE53_ZONE_ID }}
        IAM_SERVER_SSM_ARN: ${{ secrets.IAM_SERVER_SSM_ARN }}

jobs:
  deploy_to_aws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.refspec }}
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          cache: "yarn"
          cache-dependency-path: infra/${env_name}/package-lock.json
      # Update the pulumi stack with new image
      - run: |
          npm install
          pulumi stack select -c gitcoin/dpopp/${env_name}
          pulumi config -s gitcoin/dpopp/${env_name} set aws:region us-east-1 --non-interactive
        working-directory: infra/${env_name}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
            # - uses: pulumi/actions@v3
            #   id: pulumi
            #   with:
            #     command: up
            #     stack-name: gitcoin/dpopp/${env_name}
            #     upsert: false
            #     work-dir: infra/${env_name}
            #   env:
      - name: echo
        run: |
          echo PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          echo AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          echo AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          echo DOCKER_GTC_PASSPORT_IAM_IMAGE: ${{secrets.ECR_URL}}:${{ needs.build-and-test.outputs.dockerTag }}
          echo ROUTE_53_ZONE: ${{ secrets.ROUTE53_ZONE_ID }}
          echo DOMAIN: ${{ inputs.domain }}
          echo IAM_SERVER_SSM_ARN: ${{ secrets.IAM_SERVER_SSM_ARN }}
