name: Release and Deploy

on:
  workflow_call:
    inputs:
      env_name:
        required: true
        type: string
      repo_owner:
        required: true
        type: string
      repo_name:
        required: true
        type: string
      refspec:
        required: true
        type: string
      docker_tag:
        required: false
        type: string
      domain:
        required: false
        type: string

# TODO we should consolidate some of the scorer WFs and then decide what we want to keep in 
# individual repos and what we want to move here to the common repo
  
jobs:
  passport:
    if: inputs.repo_name == 'passport'
    uses: gitcoinco/gh-workflows/.github/workflows/deploy_to_aws.yml@main
    with:
      env_name: ${{ env_name }}
      repository: ${{ inputs.repo_owner }}/${{ inputs.repo_name }}
      refspec: ${{ inputs.refspec }}
      docker_tag: ${{ inputs.docker_tag }}
      domain: ${{ inputs.domain }}
    secrets:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PRODUCTION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PRODUCTION }}
      ECR_URL: ${{secrets.ECR_URL_PRODUCTION}}
      ROUTE53_ZONE_ID: ${{ secrets.ROUTE53_ZONE_ID_PRODUCTION }}
      IAM_SERVER_SSM_ARN: ${{ secrets.IAM_SERVER_SSM_ARN_PRODUCTION }}

  passport_scorer_prod:
    if: inputs.repo_name == 'passport-scorer' && inputs.env_name == 'production'
    uses: gitcoinco/passport-scorer/.github/workflows/api-promote-prod.yml
    secrets: inherit
    with:
      commit: ${{ inputs.refspec }}

  passport_scorer_prod:
    if: inputs.repo_name == 'passport-scorer' && inputs.env_name == 'staging'
    uses: gitcoinco/passport-scorer/.github/workflows/api-promote-staging.yml
    secrets: inherit
    with:
      commit: ${{ inputs.refspec }}
