name: Release and Deploy Passport

## To use this in a new repo
## 1. Copy this file
## 2. create a personal access token (with all relevant permissions including workflow write) and add to the gh secrets as TOKEN
## 3. Create an environment called "production" and add Required Reviewers

on:
  workflow_dispatch:

jobs:
  deploy_passport:
    permissions: write-all
    uses: lucianHymer/workflowTest/.github/workflows/release_and_deploy.yml@main
    with:
      owner: lucianHymer
      repo: workflowTest
      staging_frontend_branch: frontend_build_staging
      production_frontend_branch: frontend_build_prod
    secrets:
      token: ${{ secrets.TOKEN }}
