name: Release and Deploy

## Must create a personal access token and add to the gh secrets as TOKEN

on:
  workflow_dispatch:

jobs:
  deploy_passport:
    permissions: write-all
    uses: lucianHymer/workflowTest/.github/workflows/release_and_deploy.yml@main
    with:
      owner: lucianHymer
      repo: workflowTest
      staging_frontend_branch: frontend_build_staging
      production_frontend_branch: frontend_build_prod
    secrets:
      token: ${{ secrets.TOKEN }}
